<?php

function theme_event_menu(){
	$items = array();

	$items['theme_event_callback'] = array(
			'page callback' => 'theme_event_ajax_callback',
			'access arguments' => array('access content'),
			'type' => MENU_CALLBACK,
	);
	 
	return $items;
}

function theme_event_ajax_callback() {
	if(!isset($_POST["func_no"])){
		exit;
	}
	$func_no = $_POST["func_no"];
	switch($func_no){
		case 1:
			$tab_title = $_POST["title"];
			$nid = $_POST["nid"];
			$node = node_load($nid);
			$lang = $node->language;
			if($tab_title=="Home")
				echo $node->body[$lang][0]['value'];
			else {
				foreach($node->field_event_resource_title[$lang] as $index => $title) {
					if($title['value'] == $tab_title){
						$content = $node->field_event_resource[$lang][$index]['value'];
						echo $content;
						break;
					}
				}
			}
			break;
	}
}

/*
 * Implement hook_view to change display of event node view page.
 */
function theme_event_node_view($node, $view_mode, $langcode) {
	if($node->type=='event' && isset($node->field_event_resource) && !empty($node->field_event_resource)) {
		$form = array();
		$lang = $node->language;
		$src = file_create_url('public://EVR-banner.png');
		
		if(isset($node->field_header_image[$lang][0]))
			$src = file_create_url($node->field_header_image[$lang][0]['uri']);
		global $base_root, $base_path;

		$form['#attached']['js'] = array(
// 				drupal_get_library('system', 'jquery.ui')
			drupal_get_path('module', 'theme_event') . '/libraries/js/jquery.min.js',
			drupal_get_path('module', 'theme_event') . '/libraries/js/jquery-ui.min.js',
			'   var nid = ' . $node->nid . ';
				var header_img = "'. $src .'"; 
				var theme_event_callback = "' . $base_root . $base_path . 'theme_event_callback";' => array('type' => 'inline',),
			drupal_get_path('module', 'theme_event') . '/js/theme-event.js',
		);
		
		$form['#attached']['css'] = array(
			drupal_get_path('module', 'theme_event') . '/css/theme-event.css',
		);
	
		$event_tabs_str = '';
		
		foreach($node->field_event_resource_title[$lang] as $index => $title) {
			$event_tabs_str .= '<div class="div_tab" onclick="event_tab_onclick(this)">'. $title['value'] . '</div>';
		}

		$form['event_tabs'] = array(
			'#type' => 'markup',
			'#markup' => '<div class="content_tabs">
							<div class="div_tab" onclick="event_tab_onclick(this)">Home</div>' .
							$event_tabs_str .
						 '</div>',
		);
		
		$form['event_tab_content'] = array(
			'#type' => 'markup',
			'#markup' => '<div id="right_tab_content" class="tab_content">
						  </div>',
		);

		$field_event_date = $node->content['field_event_date'];
		$node->content = array($field_event_date);
		$node->content['full_vehicle_page'] = array(
			'#markup' => drupal_render($form),
		);
		
	}
}


